config/routes.rb
Iftaconferenceapp::Application.routes.draw do
  root :to => 'welcome#index', :as => :root
  #user routes
  get 'users/:id/edit_password' => 'users#edit_password', :as => :edit_user_password
  patch 'users/:id/update_password' => 'users#update_password', :as => :update_user_password
  post 'users/:id/change_role' => 'users#change_role', :as => :change_role_user
  get 'users/edit' => 'users#edit'


  #ifta member routes
  get 'members/edit' => 'ifta_members#mass_new', :as => :mass_new_members
  post 'members/new_list' => 'ifta_members#add_to_members_list', :as => :add_to_members_list
  post 'members/add_to_list' => 'ifta_members#complete_members_list', :as => :complete_members_list
  get 'members/index' => 'ifta_members#index', :as => :members

  #proposal routes
  get 'conference/:id/proposals' => 'proposals#index', :as => :conference_proposals

  devise_for :users, :controllers => { :registrations => "users/registrations", :passwords => "devise/passwords" }
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
    put 'users/password' => 'devise/passwords#update'
    post 'users/password' => 'devise/passwords#create'
    get 'users/password/edit' => 'devise/passwords#edit', :as => :edit_password
  end
  resources :users
  resources :itineraries do
    resources :proposals do
      collection do
        get 'splash', as: :splash
      end
    end
    resources :line_items
    resources :transactions
  end

  resources :payments
  post 'payments/manual' => 'payments#admin_create', :as => :manual_payment
  resources :conferences do
    collection do
      post 'select_year', as: :select_year
    end
    resources :discounts
  end
  resources :reviews

  #reports
  get 'conferences/:id/accepted_and_unregistered' => 'reports#accepted_and_unregistered', :as => :accepted_and_unregistered_report
  get 'conferences/:id/registration_breakdown' => 'reports#registration_breakdown', :as => :registration_breakdown_report
  get 'conferences/:id/student_presentations' => 'reports#student_presentations', :as => :student_presentations_report
  get 'conferences/:id/presentations' => 'reports#presentations', :as => :presentations_report
  get 'conferences/:id/presenter_proposals' => 'reports#presenter_proposals', :as => :presenter_proposals_report
  get 'conferences/:id/ceu' => 'reports#ceu', :as => :ceu_report
  get 'status' => 'welcome#status'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_paper_trail

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associaiton
  has_many :itineraries
  has_many :transactions, :through => :itineraries
  has_many :line_items, :through => :transactions
  has_many :conference_items, :through => :line_items
  has_many :payments, :through => :transactions
  has_many :reviews, foreign_key: 'reviewer_id'
  belongs_to :country
  belongs_to :ifta_member, primary_key: 'email', foreign_key: 'ifta_member_email'

  #validations
  #NOTE: validations must be conditional :unless => new_record?
  #otherwise devise can't create user
  validates :first_name, :last_name, :phone, :nametag_name, :certificate_name, :country_id, :presence => true, :unless => :new_record?
  validates :ifta_member, :presence => true, :if => :member?
  validates :emergency_name, :emergency_relationship, :emergency_telephone, :presence => true, :unless => :new_record?

  #life cycle hooks
  after_save :set_country_category #WARNING this un-drys category data from the country table

  # constants
  ROLES = %W[attendee reviewer admin]

  def country_id=(id)
    write_attribute(:country_id, id)
  end

  def self.search_for_user(options)
    options[:email] ||= ""
    options[:first_name] ||= ""
    options[:last_name] ||= ""
    where('email LIKE ? AND first_name LIKE ? AND last_name LIKE ?', options[:email] + "%", options[:first_name] + "%", options[:last_name] + "%")
  end

  def item_status(item)
    @sorted_items ||= sort_line_items
    return "Paid" if @sorted_items[:paid].include?(item.id)
    return "Pending" if @sorted_items[:unpaid].include?(item.id)
    return "--"
  end

  def item_comment(item)
    @item_comments ||= extract_line_item_comments
    return @item_comments[item.id]
  end

  def is_reviewer?
    role == 'reviewer'
  end

  def is_admin?
    role == 'admin'
  end

  def is_attendee?
    role == 'attendee'
  end

  def super_user?
    is_reviewer? || is_admin?
  end

  def itinerary_by_conference_id(conference_id)
    itineraries.where(:conference_id => conference_id).first
  end

  def reset_password(new_password, new_password_confirmation)
    if new_password.present?
      self.password = new_password
      self.password_confirmation = new_password_confirmation
      save(validate: false)
    else
      errors.add(:password, :blank)
      false
    end
  end

  private
  def set_country_category
    update_column(:country_category, Country.find(self.country_id).category) unless country_id.blank?
  end

  def sort_line_items
    sorted = {:paid => [], :unpaid => []}
    line_items.each do |line_item|
      if line_item.paid
        sorted[:paid] << line_item.conference_item_id
      else
        sorted[:unpaid] << line_item.conference_item_id
      end
    end
    return sorted
  end

  def extract_line_item_comments
    comments = {}
    line_items.each do |line_item|
      comments[line_item.conference_item_id] = line_item.comment
    end
    return comments
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

   #Adds a captcha check to the sign up process
   #this way if our sign up form gets bombed by spam bots we don't have a ton of nonsensical users
   def create
    if !verify_recaptcha
      flash.delete :recaptcha_error
      build_resource
      resource.valid?
      resource.errors.add(:base, "There was an error with the recaptcha code below. Please re-enter the code.")
      clean_up_passwords(resource)
      respond_with_navigational(resource) { render :new }
    elsif user_exists?
      redirect_to new_user_session_path, alert: t('.email_in_use')
    else
      flash.delete :recaptcha_error
      flash[:errors] = 'hide'
      super
    end
  end

  private

  def user_exists?
    User.find_by(email: params[:user][:email]).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def index
    @conference = selected_conference
    @conference_items = @conference.conference_items
    @users = User.search_for_user(params).includes(:line_items).page(params[:page]).per_page(150) #search is an intersection not union
    authorize! :list, User
  end

  def edit
    #I redirected the devise edit route (which doesn't put the user id in the URL) to this action,
    #fall back on current_user
    @user = User.find(params[:id] || current_user.id)
    authorize! :update, @user
  end


  def update
    @user = User.find(params[:id] || current_user)
    authorize! :update, @user

    if @user.update(user_params)
      flash[:notice] = 'Account successfully updated.'
      redirect_to after_sign_in_path_for(current_user)
    else
      render :action => 'edit'
    end

  end


  def change_role
    @user = User.find(params[:id])
    authorize! :change_role, @user
    @user.role = params[:new_role]
    if @user.save
      flash[:notice] = "Successfully changed #{@user.first_name} #{@user.last_name}'s role to #{params[:new_role]}"
      redirect_to after_sign_in_path_for(current_user)
    else
      flash[:alert] = "Could not change #{@user.first_name} #{@user.last_name}'s  role to #{params[:new_role]}"
      render :action => 'edit'
    end
  end

  def edit_password
    @user = User.find(params[:id])
    authorize! :update, @user
  end


  def update_password
    @user = User.find(params[:id])
    authorize! :update, @user
    if @user.update_with_password(user_params) #devise helper method, prevents updating password without current password
      sign_in @user, :bypass => true
      redirect_to after_sign_in_path_for(@user)
    else
      render "edit_password"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :remember_me,
        :first_name, :last_name, :prefix, :initial, :suffix, :address,
        :city, :state, :country_id, :zip, :phone, :username, :member,
        :student, :ifta_member_email, :fax_number, :emergency_name,
        :emergency_relationship, :emergency_telephone, :emergency_email,
        :nametag_name, :certificate_name, :current_password)
    end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_contact_info.html.erb
<h1>Personal Information</h1>
<%= simple_form_for @user, :html => {:class => 'contact-form'} do |f| %>
	<%= render :partial => 'shared/error_messages', :locals => {:object => @user} %>

	<h3>Name</h3>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :prefix %>
	<%= f.input :initial %>
	<%= f.input :suffix %>

	<h3>Nametag &amp; Certificate</h3>
	<p><em>Please type your name as you would like it to appear on your name badge and participation certificate.</em></p>
	<%= f.input :nametag_name %>
	<%= f.input :certificate_name %>

	<h3>Residency</h3>
	<%= f.association :country %>
	<%= f.input :state %>
	<%= f.input :address %>
	<%= f.input :city %>
	<%= f.label 'Zip'%>
	<%= f.text_field :zip %>

	<h3>Other</h3>
	<em>Please include country and area codes e.g. 12223334444</em><br>
	<%= f.label 'Phone number' %>
	<%= f.text_field :phone, class: 'phone_number' %><br>
	<%= f.label 'Fax number' %>
	<%= f.text_field :fax_number, class: 'phone_number' %>
	<%= f.input :email %>
	<%= f.label :student, 'Student?' %>
	<%= f.check_box :student %><em>(Yes)</em><br>
	<em><b>Note:</b> After you send your student confirmation to info@ifta-congress.org you will recieve a student discount code. For more details check out the student registration section <a href="http://www.ifta-congress.org/registration_fees.php" target="_blank">here</a></em><br>
	<%= f.label :member, 'IFTA Member?' %>
	<%= f.check_box :member %><em>(Yes)</em><br>
	<%= f.input :ifta_member_email, label: 'Member Email' %>

	<h3>Emergency Contact Information</h3>
	<%= f.input :emergency_name, :label => 'Contact name' %><br>
    <%= f.input :emergency_relationship, :label => 'Relationship to contact' %><br>
    <%= f.input :emergency_telephone,  :input_html => {class: 'phone_number'}  %><br>
    <%= f.input :emergency_email %><br>

	<p>FYI If you would like an invitation letter for visa or funding purposes you MUST pay for the conference first,
		<br>then <%= link_to 'check out this page', 'http://www.ifta-congress.org/invitation_letter_request.php', target: '_blank' %> to request your invitation.</p>
	<%= f.button :submit, :class => 'btn submit' %>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
	<div class="btn btn-primary">
	  <%= link_to "Sign in", new_session_path(resource_name) %>
	</div>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
	<div class="btn btn-primary">
	  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
	</div>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_sign_in.html.erb
<h2>Sign in (Returning Users)</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "form-horizontal"}) do |f| %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, required: true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, minlength: 6, required: true %>
    </div>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="control-group">
      <%= f.label :remember_me, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :remember_me %>
      </div>
    </div>
  <% end -%>

  <div>
    <%= f.submit "Sign in", :class => 'btn submit' %>
  </div>

  <br>
  <div class="btn btn-warning">
    <%= link_to "Forgot your password?", new_user_password_path %>
  </div>
<% end %>

app/views/users/shared/_sign_up.html.erb
<h2>Sign up (New Users)</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-horizontal'}) do |f| %>
  <%=
  #override this method in the DeviseHelper module to use the application error_messages partial
  devise_error_messages! %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, required: true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, minlength: 6, required: true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, minlength: 6, required: true %>
    </div>
  </div>

  <%= recaptcha_tags %>

  <div>
    <%= f.submit "Sign up", :class => 'btn submit' %>
  </div>
<% end %>