config/routes.rb
Iftaconferenceapp::Application.routes.draw do
  root :to => 'welcome#index', :as => :root
  #user routes
  get 'users/:id/edit_password' => 'users#edit_password', :as => :edit_user_password
  patch 'users/:id/update_password' => 'users#update_password', :as => :update_user_password
  post 'users/:id/change_role' => 'users#change_role', :as => :change_role_user
  get 'users/edit' => 'users#edit'


  #ifta member routes
  get 'members/edit' => 'ifta_members#mass_new', :as => :mass_new_members
  post 'members/new_list' => 'ifta_members#add_to_members_list', :as => :add_to_members_list
  post 'members/add_to_list' => 'ifta_members#complete_members_list', :as => :complete_members_list
  get 'members/index' => 'ifta_members#index', :as => :members

  #proposal routes
  get 'conference/:id/proposals' => 'proposals#index', :as => :conference_proposals

  devise_for :users, :controllers => { :registrations => "users/registrations", :passwords => "devise/passwords" }
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
    put 'users/password' => 'devise/passwords#update'
    post 'users/password' => 'devise/passwords#create'
    get 'users/password/edit' => 'devise/passwords#edit', :as => :edit_password
  end
  resources :users
  resources :itineraries do
    resources :proposals do
      collection do
        get 'splash', as: :splash
      end
    end
    resources :line_items
    resources :transactions
  end

  resources :payments
  post 'payments/manual' => 'payments#admin_create', :as => :manual_payment
  resources :conferences do
    collection do
      post 'select_year', as: :select_year
    end
    resources :discounts
  end
  resources :reviews

  #reports
  get 'conferences/:id/accepted_and_unregistered' => 'reports#accepted_and_unregistered', :as => :accepted_and_unregistered_report
  get 'conferences/:id/registration_breakdown' => 'reports#registration_breakdown', :as => :registration_breakdown_report
  get 'conferences/:id/student_presentations' => 'reports#student_presentations', :as => :student_presentations_report
  get 'conferences/:id/presentations' => 'reports#presentations', :as => :presentations_report
  get 'conferences/:id/presenter_proposals' => 'reports#presenter_proposals', :as => :presenter_proposals_report
  get 'conferences/:id/ceu' => 'reports#ceu', :as => :ceu_report
  get 'status' => 'welcome#status'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  #associations
  belongs_to :order, class_name: "Transaction", foreign_key: 'transaction_id' # rails 4 reserved transaction method, rename to order


  #life cycle hooks
  after_save :mark_transaction
  before_destroy :clear_transaction

  serialize :params
  delegate :user, :to => :order

  private

  def mark_transaction
    order.paid = confirmed
    order.save
  end

  def clear_transaction
    order.paid = false
    order.save
  end
end

app/controllers/payments_controller.rb
require "paypal_callback"

class PaymentsController < ApplicationController
  #let paypal access the create action as an anynonmous user
  protect_from_forgery :except => :create
  skip_before_action :authenticate_user!, :only => :create

  #This action only handles the Payments created through the PayPal IPN Process
  def create
    #PaypalCallback object sends the raw post request to paypal and expects to get VERIFIED back
    response = PaypalCallback.new(params, request.raw_post, ENV["PAYPAL_POST_URL"])

    #check that the payment says completed & paypal verifies post content
    if response.completed? && response.valid?
      @transaction = Transaction.find(params[:invoice]) #invoice is a pass through variable that gets embedded in the encrpyted paypal form and we get it back here
      Payment.create(:transaction_id => @transaction.id, :amount => params['payment_gross'], :confirmed => true)
    else
      #TODO maybe send out some type of alert to an admin
    end
    head :ok
  end

  def new
    @conference = selected_conference
    @payment = Payment.new
    @transactions = Transaction.search_for_transactions(params).page(params[:page]).per_page(20).includes(:itinerary => [:user], :line_items => [:conference_item])
    authorize! :create, @payment
  end

  #When IFTA gets checks or bank transfers the event planners have to mark the payments in the system as paid
  def admin_create
    @payment = Payment.new(payment_params)
    authorize! :create, @payment
    if @payment.save
      PaymentMailer.payment_notification(@payment).deliver if params[:send_email]
      redirect_to after_sign_in_path_for(current_user)
    else
      render :action => 'new'
    end
  end

  def update
    @payment = Payment.find(params[:id])
    authorize! :update, @payment
    if @payment.update(payment_params)
      render "update", :locals => {:notice_message => 'Successfully Updated Payment'}
    else
      render :partial => 'shared/error_messages', :locals => {:object => @line_item}
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    authorize! :destroy, @payment
    @payment.destroy
    redirect_to after_sign_in_path_for(current_user)
  end

  private
    def payment_params
      params.require(:payment).permit(:transaction_id, :amount, :params, :confirmed, :comments)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment.html.erb
<div class='mark_as_paid'>
<%= form_for payment, :url => manual_payment_path do |f| %>
		<%= f.hidden_field :transaction_id, :value => transaction.id %>
		<%= f.hidden_field :confirmed, :value => true %>
		<div class="control-group">
			<%= f.label :amount, 'Amount $', :class => 'control-label' %>
			<%= f.text_field :amount, :size => 5, :value => sprintf("%.2f", transaction.post_tax_total) %>
		</div>
		<div class="control-group">
			<%= f.label :comments, 'Comments', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_area :comments, :rows => 2, :cols => 20 %>
			</div>
		</div>

		<%= label_tag :send_email, 'Send Email', :class => 'control-label' %>
		<%= check_box_tag :send_email, true, :checked => :checked %><br>

		<%= f.submit "Mark As Paid", :class => 'btn btn-primary' %>
<%- end %>
<%= button_to "Delete Transaction", itinerary_transaction_path(transaction.itinerary, transaction), method: :delete, :class => 'destroy btn btn-danger deleteTransaction' %>
</div>

app/views/payments/_payment_options.html.erb
<span class='payment_option'>
<%= form_for payment, :remote => true do |f| %>
	<div class="control-group">
		<%= f.label :amount, 'Paid: $', :class => 'control-label' %>
		<%= f.text_field :amount, :size => 5 %><br>
	</div>

	<div class="control-group">
		<%= f.label :comments, 'Comments', :class => 'control-label' %>
		<div class='controls'>
			<%= f.text_area :comments, :rows => 2, :cols => 20 %>
		</div>
	</div>

	<%= f.submit 'Update Payment', :class => 'btn btn-primary' %>
<%- end %>
</span>
<span class='payment_option'><%= button_to "Delete", payment, method: :delete, :class => 'destroy btn btn-danger' %></span>

app/views/payments/_transaction.html.erb
<div <%- if transaction.paid -%> class='paid'<%- else -%>class='unpaid'<%- end -%>>

<%= transaction.user.first_name + " " + transaction.user.last_name -%><br>
Method: <%= transaction.payment_method %><br>
<%- transaction.line_items.each do |line_item| %>
	<%= line_item.conference_item.name %>
	$<%= sprintf "%.2f", line_item.price %><br>
<%- end %>

<strong>Total: $<%= sprintf "%.2f", transaction.post_tax_total %></strong><br>

<%- if transaction.paid -%>
	--------------<br>
	<%= render 'payment_options', :payment => transaction.payment %>
<%- else -%>
		<%= render 'payment', :payment => @payment, :transaction => transaction %>
<%- end -%>

</div>

<hr>

app/views/payments/new.html.erb
<%- content_for :nav do %>
	<%= render :partial => "layouts/admin_nav" %>
<%- end %>

<h1>Search Transactions</h1>
<%= form_tag new_payment_path, :method => 'get', :class => 'form-horiztontal' do %>

	<%= hidden_field_tag :conference_id, selected_conference.id %>

	<%= label_tag :Paid, 'Paid' %>
	<%= check_box_tag :paid, 'true', params[:paid]%>

	<%= label_tag :Unpaid, 'Unpaid' %>
	<%= check_box_tag :unpaid, 'true', params[:unpaid] %>

	<div class="control-group">
		<%= label_tag :first_name, 'First Name', :class => 'control-label' %>
		<div class='controls'>
			<%= text_field_tag :first_name, params[:first_name] %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag :last_name, 'Last Name', :class => 'control-label' %>
		<div class="controls">
			<%= text_field_tag :last_name, params[:last_name] %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag :email, 'Email', :class => 'control-label' %>
		<div class='controls'>
			<%= text_field_tag :email, params[:email] %>
		</div>
	</div>

	<%= submit_tag :Search, :class => 'btn btn-primary' %>
	<br>
<%-end%>

<div class="digg_pagination">
<%= will_paginate @transactions %><br><br>
</div>
<%= render :partial => 'transaction', :collection => @transactions %>
<Br><Br>

app/views/payments/update.js.erb
<%# Remove any lingering alert messages %>
$('.alert').remove()

<%#display the flash message%>
<%= render(:partial => 'shared/notice_message', :locals => {:notice_message => notice_message}) %>
$('.notice').delay(3000).fadeOut();