config/routes.rb
Iftaconferenceapp::Application.routes.draw do
  root :to => 'welcome#index', :as => :root
  #user routes
  get 'users/:id/edit_password' => 'users#edit_password', :as => :edit_user_password
  patch 'users/:id/update_password' => 'users#update_password', :as => :update_user_password
  post 'users/:id/change_role' => 'users#change_role', :as => :change_role_user
  get 'users/edit' => 'users#edit'


  #ifta member routes
  get 'members/edit' => 'ifta_members#mass_new', :as => :mass_new_members
  post 'members/new_list' => 'ifta_members#add_to_members_list', :as => :add_to_members_list
  post 'members/add_to_list' => 'ifta_members#complete_members_list', :as => :complete_members_list
  get 'members/index' => 'ifta_members#index', :as => :members

  #proposal routes
  get 'conference/:id/proposals' => 'proposals#index', :as => :conference_proposals

  devise_for :users, :controllers => { :registrations => "users/registrations", :passwords => "devise/passwords" }
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
    put 'users/password' => 'devise/passwords#update'
    post 'users/password' => 'devise/passwords#create'
    get 'users/password/edit' => 'devise/passwords#edit', :as => :edit_password
  end
  resources :users
  resources :itineraries do
    resources :proposals do
      collection do
        get 'splash', as: :splash
      end
    end
    resources :line_items
    resources :transactions
  end

  resources :payments
  post 'payments/manual' => 'payments#admin_create', :as => :manual_payment
  resources :conferences do
    collection do
      post 'select_year', as: :select_year
    end
    resources :discounts
  end
  resources :reviews

  #reports
  get 'conferences/:id/accepted_and_unregistered' => 'reports#accepted_and_unregistered', :as => :accepted_and_unregistered_report
  get 'conferences/:id/registration_breakdown' => 'reports#registration_breakdown', :as => :registration_breakdown_report
  get 'conferences/:id/student_presentations' => 'reports#student_presentations', :as => :student_presentations_report
  get 'conferences/:id/presentations' => 'reports#presentations', :as => :presentations_report
  get 'conferences/:id/presenter_proposals' => 'reports#presenter_proposals', :as => :presenter_proposals_report
  get 'conferences/:id/ceu' => 'reports#ceu', :as => :ceu_report
  get 'status' => 'welcome#status'
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  #object versioning, don't let the users delete yo data!
  has_paper_trail

  #associations
  has_many :presenters, :dependent => :destroy
  has_many :reviews
  belongs_to :itinerary
  belongs_to :conference
  belongs_to :user

  accepts_nested_attributes_for :presenters, allow_destroy: true

  #query
  scope :current, ->(conference_id = Conference.active.id){ joins('INNER JOIN conferences ON conferences.id = proposals.conference_id').where('conference_id = ?', conference_id)}
  scope :unreviewed, -> { where(:status => nil) }
  scope :reviewed, -> { joins(:reviews) }
  scope :accepted, -> { where(:status => 'accept') }
  scope :wait_listed, -> { where(:status => 'wait list') }

  #validations
  validate :short_description_max_words
  validate :long_description_max_words
  validates :format, :category, :title, :short_description, :relative_number, :itinerary, :conference, :learning_objective, :presence => true
  validates_associated :presenters
  validates :presenters, :length => {:maximum => 4, :message => 'the maximum number of presenters is 4'}
  validates :agree, :acceptance => {:accept => true}
  validate :check_av_requirements

  #life cycle hooks
  before_validation :add_relative_number

  def self.accepted_and_unregistered(conference)
    report = {}
    conference.proposals.where(:status => 'accept').includes(:presenters).find_each do |proposal|
      proposal.presenters.each do |presenter|
        report[proposal.id] ||= {
          :proposal_title => proposal.title,
          :accepted_on => proposal.updated_at,
          :presenters => []
        } # initialize each proposal once
        report[proposal.id][:presenters] << {
          :first_name => presenter.first_name,
          :last_name => presenter.last_name,
          :email => presenter.email,
          :status => Presenter.presenter_conference_status(presenter.email, conference.id)
        }
      end
    end
    return report
  end

  def add_self_as_presenter
    presenters.build({
      first_name: user.first_name,
      last_name: user.last_name,
      home_telephone: user.phone,
      email: user.email,
      country_id: user.country.id
    })
  end

  private

    def check_av_requirements
      if (projector.present? || sound.present?) && no_equipment.present?
        errors.add(:no_equipment, 'You cannot select no equipment with other options')
      end

      if no_equipment.blank? && projector.blank? && sound.blank?
        errors.add(:no_equipment, 'Please select one of the AV options.')
      end

      if format == '20min' && (projector.present? || sound.present?)
        errors.add(:format, '20 minutes does not allow AV equipment')
      end
    end

    def self.search(options)
      proposals = Proposal.current(options[:conference_id])
      #Requests to the proposals index controller should have a hash called query whose keys are the proposal statuses you want returned
      #default behavior is to return proposals with no status
      options[:query].blank? ? proposals.where('proposals.status IS NULL') : proposals.where('proposals.status IN (?)', options[:query].keys.join(", ").sub('_', ' '))
    end

    def self.next_relative_number(conference_id)
      proposal = where(conference_id: conference_id).where('relative_number IS NOT NULL').order('relative_number DESC').first
      (proposal.present? ? proposal.relative_number : 0) + 1
    end

    def add_relative_number
      self.relative_number = Proposal.next_relative_number(conference_id) if relative_number.blank?
    end

    def short_description_max_words
      count = short_description.scan(/\w+/).count
      if count  > 50
        errors.add(:short_description, "max words is 50 and you have #{count}")
      end
    end

    def long_description_max_words
      count = long_description.scan(/\w+/).count
      if count > 300
        errors.add(:long_description, "max words is 300 and you have #{count}")
      end
    end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :check_contact_info

  #There can be different proposal forms to choose from but they are all different representations of one proposal model
  #the links on the splash page are just pass information to the new action ie. student
  def splash
    @itinerary = Itinerary.find(params[:itinerary_id])
    authorize! :update, @itinerary
  end

  #At the moment student is the only query parameter but this design is easily extensible
  def new
    @itinerary = Itinerary.includes(:user).find(params[:itinerary_id])
    student = params[:student] == 'yes'
    @proposal = @itinerary.proposals.build(student: student)
    @proposal.user = @itinerary.user
    @proposal.add_self_as_presenter
    authorize! :create, @proposal
  end

  #Nothing special here, proposal model takes care of nested presenter models.  Gotta love Rails :)
  def create
    @itinerary = Itinerary.includes([:conference, :user]).find(params[:itinerary_id])
    @proposal = @itinerary.proposals.build(proposal_params)
    @proposal.conference = @itinerary.conference
    @proposal.user = @itinerary.user
    authorize! :create, @proposal
    if @proposal.save
      flash[:notice] = "Thank you for your proposal submission."
      redirect_to after_sign_in_path_for(current_user)
    else
      render :action => "new"
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:itinerary_id])
    @proposal = Proposal.find(params[:id])
    authorize! :update, @proposal
  end

  def update
    @itinerary = Itinerary.find(params[:itinerary_id])
    @proposal = Proposal.find(params[:id])
    authorize! :update, @proposal
    if @proposal.update(proposal_params)
      redirect_to after_sign_in_path_for(current_user), :notice => 'Proposal successfully updated.'
    else
      render :action => 'edit'
    end
  end

  #reviewers can review proposals right from the search results
  def index
    authorize! :index, Proposal
    @proposals = Proposal.search(params) #search returns an intersection not union
    @proposals = @proposals.page(params[:page]).per_page(150).includes(:itinerary, :presenters)
    @review = Review.new
  end

  private
    def proposal_params
      params.require(:proposal).permit(:format,
       :category,
       :title,
       :title_non_english,
       :short_description,
       :short_description_non_english,
       :long_description,
       :long_description_non_english,
       :student,
       :agree,
       :no_equipment,
       :sound,
       :projector,
       :keywords,
       :language_english,
       :language_spanish,
       :language_portuguese,
       :language_mandarin,
       :language_japanese,
       :language_korean,
       :language_malay,
       :learning_objective,
        presenters_attributes: [:id,
         :_destroy,
         :first_name,
         :last_name,
         :home_telephone,
         :work_telephone,
         :fax_number,
         :country_id,
         :email,
         :affiliation_name,
         :affiliation_position,
         :graduating_institution,
         :highest_degree,
         :qualifications,
         :registered,
         :other_presentations,
         :other_emails]
      )
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper

  def keyword_options
    [["Abuse and Domestic Violence",
      [
        "Bullying",
        "Emotional Abuse",
        "Physical Abuse: Child, Partner, Elder"
      ]
    ],
    ["Consultation and Collaboration On:",
      [
        "Collaborative Care",
        "Community Issues and Systems",
        "Homelessness, Migration, Resettlement",
        "Medical Issues and Systems"
      ]
    ],
    ["Education and Training of Therapists",
      [
        "Educational Preparation",
        "Clinical Training",
        "Supervision",
        "Therapy and Personal Growth",
        "Program Development",
        "Systemic Theory"
      ]
    ],
    ["Family Development",
      [
        "Clinical Implications of Family Development",
        "Theories of Family Development and Clinical Interventions",
        "Child Development and Its Implications",
        "Parenting"
      ]
    ],
    ["Legal Regulation of Therapy/Therapists",
      [
        "Certification, Licensure, Regulation Issues"
      ]
    ],
    ["Research: Evaluation of Therapy",
      [
        "Evidence Based Treatment",
        "Methodology",
        "Outcome Research",
        "Process Research",
        "State of Knowledge"
      ]
    ],
    ["Therapy",
      [
        "Couple and Marital Therapy",
        "Family Therapy"
      ]
    ],
    ["Trauma and Healing",
      [
        "Accident and Injury",
        "Natural Catastrophe",
        "Terrorism",
        "Torture",
        "War/Political"
      ]
    ],
    ["Other",
      [
        "Coaching",
        "Death Dying, Bereavement, Loss",
        "Divorce and Remarriage",
        "Legal Systems and Courts",
        "Mental Health and Illness",
        "Spirituality",
      ]
    ]]
  end

  def show_languages(proposal)
    languages = ""
    languages += "English, " if proposal.language_english
    languages += "Mandarin, " if proposal.language_mandarin
    languages += "Japanese, " if proposal.language_japanese
    languages += "Korean, " if proposal.language_korean
    languages.chomp(", ")
  end

  # IFTA only has one review per proposal
  # loading the most recent review or creating a new review
  def current_review(proposal)
    proposal.reviews.last || Review.new
  end
end

app/views/proposals/_form.html.erb
<%= simple_form_for [@itinerary, @proposal], :html => {:class => 'form-horizontal'}  do |f| %>

<%= render :partial => 'shared/error_messages', :locals => {:object => @proposal} %>

<%= f.hidden_field :student %>
<h3>Language</h3>
<p>Workshops will be presented in English.  Please tell us which languages you speak fluently and would be willing to speak in your workshop.  Check as many as apply.
The Program Committee will make the decision as which language you will present in based on the number and balance of the proposals.  </p>

<%= f.label :language_english, 'English' %>
<%= f.check_box :language_english %><br>
<hr>

<h3>Presentation Format</h3>
	<%= f.radio_button :format, "poster"%>
  <%= f.label :format_poster do %>
	 <span>
    Poster Display
    <em>(Limit four presenters)</em>
   </span>
  <% end %>
  <br>
	<%= f.radio_button :format, "20min", data: { disable_av: true} %>
  <%= f.label :format_20min do %>
	  <span>
      20 minutes
      <em>(Limit two registered presenters, these presentations won't have Audio Visual available)</em>
    </span>
  <% end %>
  <br>
	<%= f.radio_button :format, "45min" %>
  <%= f.label :format_45min do %>
	 <span>45 minutes
    <em>(Limit to four registered presenters)</em>
   </span>
  <% end %>
<hr>

<h3>Audio Visual Needs</h3>
<div>
  <span class="important_reminder">Please note that there is no wireless internet in the rooms!</span><br>
  <%= f.input :no_equipment, :label => "No Equipment Needed"%>
  <%= f.input :projector, :label => "LCD Projector"%>
  <%= f.input :sound, :label => "Sound (to play video)"%>
</div>

<h3>Category of Information to be presented</h3>
	<%= f.radio_button :category, "clinical"%> <%= f.label :category_clinical, 'Clinical' %><br>
	<%= f.radio_button :category, "research"%> <%= f.label :category_research, 'Research' %><br>
	<%= f.radio_button :category, "theoretical"%> <%= f.label :category_theoretical, 'Theoretical' %><br>
	<%= f.radio_button :category, "training"%> <%= f.label :category_training, 'Training & Supervision' %><br>
	<%= f.radio_button :category, "policy"%> <%= f.label :category_policy, 'Social Policy' %><br>
	<%= f.radio_button :category, "justice"%> <%= f.label :category_justice, 'Social Justice' %><br>
	<%= f.radio_button :category, "founders"%> <%= f.label :category_founders, 'Founders' %><br>
	<%= f.radio_button :category, "innovative"%> <%= f.label :category_innovative, 'Innovative' %><br>
<hr>

<h3>Keyword</h3>
	<%= f.label :keywords, 'Keyword' %>
	<%= f.select :keywords, grouped_options_for_select(keyword_options, @proposal.keywords), {:include_blank => true}%>
<hr>
<h3>Title</h3>
	<%= f.label :title, "Title of Abstract:"%>
	<%= f.text_field  :title %> <br>
	(90 characters max, including spaces) <br>
  <%= f.label :title_non_english, "Title of Abstract in your First Language:"%>
	<%= f.text_field  :title_non_english %> <br>
<hr>
<h3>Short Description (published in Program Guide)</h3>
	<%= f.label "(50 words max)"%>
	<%= f.text_area :short_description, {cols: '60', rows: '6', required: true} %>
<h3>Short Description in your Non-English Presentation Language</h3>
	<%= f.label "(50 words max)"%>
	<%= f.text_area :short_description_non_english, {cols: '60', rows: '6'} %>
<hr>
<h3>Long Description (published in Book of Abstracts)</h3>
	<%= f.label :long_description, "(300 words max)"%>
	<%= f.text_area :long_description, {cols: '60', rows: '20'} %>
<h3>Long Description in your Non-English Presentation Language – NOT REQUIRED</h3>
	<%= f.label "(300 words max)"%>
	<%= f.text_area :long_description_non_english, {cols: '60', rows: '20'} %>
<hr>

<h3>Learning Objective</h3>
  Complete this sentence:  "After this workshop, the learner will be able to… (do something, or state something, or list something or differentiate something) <em>(Do not use the word Understand)</em>
  <br>
  <%= f.text_area :learning_objective, cols: 60, rows: 3, required: true  %>
<hr>

<br>
Note: Presenters must bring their own laptop

<h3>Presenters</h3>
<%= f.simple_fields_for :presenters do |builder|%>
	<%= render 'presenter_fields', f: builder %>
<% end %>

<%= link_to_add_fields "Add Presenter", f, :presenters %>

<br>

<p>In submitting this abstract, I agree that if this proposal is selected, I and any co-presenters will register for the full Congress within a month of being notified of 'Accepted' Status.<br>
<%= f.label :agree, "I agree" %>
<%= f.check_box :agree %>
</p>
<br>
<%= f.button :submit, :class => 'btn submit' %>

<% end %>

app/views/proposals/_presenter_fields.html.erb
<fieldset class="show-fieldset">
	<%= render :partial => 'shared/error_messages', :locals => {:object => f.object} %>

	<%= f.input :first_name, label: "First name" %>
	<%= f.input :last_name, label: "Last name" %>

	<em>Please include country and area codes e.g. 12223334444</em><br>
	<%= f.label 'Home phone' %><%= f.text_field :home_telephone, class: 'phone_number' %><br>
	<%= f.label 'Work phone' %><%= f.text_field :work_telephone, class: 'phone_number' %><br>
	<%= f.label 'Fax number' %><%= f.text_field :fax_number, class: 'phone_number' %><br>
  <%= f.association :country %>

	<%= f.input :email %>

	<%= f.input :affiliation_name, label: "Affiliation Name", placeholder: "e.g. university, clinic, etc" %>

	<%= f.input :affiliation_position, label: "Affiliation Position " %>

	<%= f.input :highest_degree, label: "Terminal or Highest Degree" %>
	<%= f.input :graduating_institution, label: "Graduating Institution" %>

	<br>
	<%= f.label "What qualifies you to present on this topic" %>
	<br>
	<%= f.text_area :qualifications, rows: 3, cols: 80, placeholder: "e.g., degrees, trainings, certifications with dates" %>

	<br>
	<%= f.label :registered, "Is this person currently registered for the conference? " %>
	<%= f.check_box :registered %><em>(Yes)</em><br>
	<%= f.label :other_presentations, "Is this person currently listed as a presenter on any other proposals? " %>
	<%= f.check_box :other_presentations %><em>(Yes)</em><br>
	<br>
	<p>If you answered yes to the question above and this person is using alternative email addresses please list any additional email addresses below (separated by commas)</p>
	<%= f.input :other_emails %>
	<%= f.hidden_field :_destroy %>
  	<%= link_to "Remove Presenter", "#", :class => "btn btn-danger remove_fields" %>

</fieldset>

app/views/proposals/_proposal.html.erb
<h3>Title: <%= proposal.title %></h3>
<em>Short Description: </em><%= proposal.short_description %><br>
<em>Long Description: </em><%= proposal.long_description %><br>
<em>Presenters: </em>
<% proposal.presenters.collect(&:full_name).join(', ') %>
<br>
<hr>

app/views/proposals/edit.html.erb
<h1>Edit Proposal</h1>
<%= render "form" %>

app/views/proposals/index.html.erb
<%- content_for :nav do %>
	<%= render :partial => "layouts/reviewer_nav" %>
<%- end %>

<h1>Proposals</h1>
<%= render :partial => 'shared/error_messages', :locals => {:object => @review } unless @review.blank? %>

<div class="digg_pagination">
<%= will_paginate @proposals %><br><br>
</div>

<%- if !@proposals.blank? %>
	<%= render partial: 'reviews/review_proposal', collection: @proposals, :as => :proposal  %>
<%- else %>
	<p>No unreviewed proposals</p>
<%- end %>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>
<%= render "form" %>

app/views/proposals/splash.html.erb
<h1>Call For Proposals</h1>

<p>Participants interested in making presentations or poster displays are invited to submit an abstract. Proposals must be submitted via the congress website.</p>

<table>
	<tr>
		<td>Click here for the <%= link_to "General Submissions", new_itinerary_proposal_path(@itinerary) %> form.</td>
		<td>Read the <a href="http://www.ifta-congress.org/docs/GeneralGuidelines.pdf" target="_blank">General Guidelines</a>.</td>
	</tr>
	<tr>
		<td>Click here for the <%= link_to "Student Submissions", new_itinerary_proposal_path(@itinerary, :student => 'yes') %> form.</td>
		<td>Read the <a href="http://www.ifta-congress.org/docs/CallforProposalsStudents.pdf" target="_blank">Student Guidelines</a>.</td>
	</tr>
</table>

<h3>LANGUAGE</h3>
<p>The official language of the meeting is English. All abstract submissions and presentations are to be in English.
</p>

<h3>PLENARIES</h3>
<p>The Plenary Sessions by the keynote presenters will be in English, Spanish, and Portuguese.</p>

<h3>Limit to Number of Acceptances</h3>
<p>If more than two proposals are submitted by a main presenter, the selection process will limit acceptances to no more than two presentations that best fit the Congress theme or help to round out the Congress program.</p>